import{a as h,S as g}from"./assets/vendor-DBMDmZZa.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="47406672-32912a9d4734ffdd3d590f70b",L="https://pixabay.com/api/",w=15,u=async(t,r=1)=>{var s,e;const a={key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:w};try{const{data:o}=await h.get(L,{params:a});if(o.totalHits===0)throw new Error("No images found for your query.");return o}catch(o){throw new Error(((e=(s=o.response)==null?void 0:s.data)==null?void 0:e.message)||"Failed to fetch images.")}},v=t=>t.map(({webformatURL:r,largeImageURL:a,tags:s,likes:e,views:o,comments:n,downloads:f})=>`
    <div class="photo-card">
      <a href="${a}" class="gallery__item">
        <img src="${r}" alt="${s}" loading="lazy" class="gallery__image" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${o}</p>
        <p><b>Comments:</b> ${n}</p>
        <p><b>Downloads:</b> ${f}</p>
      </div>
    </div>`).join(""),S=()=>new g(".gallery__item",{captionsData:"alt",captionDelay:250}),_=()=>{var r;const t=((r=document.querySelector(".photo-card"))==null?void 0:r.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})},E=document.querySelector("#search-form"),y=document.querySelector(".gallery"),i=document.querySelector(".load-more");let d,l="",c=1;i.style.display="none";const P=async t=>{if(t.preventDefault(),l=t.currentTarget.elements.searchQuery.value.trim(),!l){alert("Please enter a search query.");return}y.innerHTML="",c=1,i.style.display="none";try{const r=await u(l,c);m(r.hits),p(r.totalHits)}catch(r){alert(r.message)}},q=async()=>{c+=1;try{const t=await u(l,c);m(t.hits),p(t.totalHits),_()}catch(t){alert(t.message)}},m=t=>{const r=v(t);y.insertAdjacentHTML("beforeend",r),d?d.refresh():d=S()},p=t=>{c*15>=t?(i.style.display="none",alert("We're sorry, but you've reached the end of search results.")):i.style.display="block"};E.addEventListener("submit",P);i.addEventListener("click",q);
//# sourceMappingURL=index.js.map
