import{a as g,S as b,i as n}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L="47406672-32912a9d4734ffdd3d590f70b",w="https://pixabay.com/api/",E=15,p=async(o,t=1)=>{var s,e;const a={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:E};try{const{data:r}=await g.get(w,{params:a});if(r.totalHits===0)throw new Error("No images found for your query.");return r}catch(r){throw new Error(((e=(s=r.response)==null?void 0:s.data)==null?void 0:e.message)||"Failed to fetch images.")}},v=o=>o.map(({webformatURL:t,largeImageURL:a,tags:s,likes:e,views:r,comments:i,downloads:f})=>`
    <div class="photo-card">
      <a href="${a}" class="gallery__item">
        <img src="${t}" alt="${s}" loading="lazy" class="gallery__image" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e}</p>
        <p><b>Views:</b> ${r}</p>
        <p><b>Comments:</b> ${i}</p>
        <p><b>Downloads:</b> ${f}</p>
      </div>
    </div>`).join(""),P=()=>new b(".gallery__item",{captionsData:"alt",captionDelay:250}),S=()=>{var t;const o=((t=document.querySelector(".photo-card"))==null?void 0:t.getBoundingClientRect().height)||0;window.scrollBy({top:o*2,behavior:"smooth"})},_=document.querySelector("#search-form"),h=document.querySelector(".gallery"),c=document.querySelector(".load-more");let u,d="",l=1;c.style.display="none";const q=async o=>{if(o.preventDefault(),d=o.currentTarget.elements.searchQuery.value.trim(),!d){n.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}h.innerHTML="",l=1,c.style.display="none";try{const t=await p(d,l);if(t.hits.length===0){n.error({title:"Error",message:"No images found. Try another search query.",position:"topRight"});return}m(t.hits),y(t.totalHits)}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}},R=async()=>{l+=1;try{const o=await p(d,l);m(o.hits),y(o.totalHits),S()}catch{n.error({title:"Error",message:"Failed to fetch more images. Please try again later.",position:"topRight"})}},m=o=>{const t=v(o);h.insertAdjacentHTML("beforeend",t),u?u.refresh():u=P()},y=o=>{l*15>=o?(c.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):c.style.display="block"};_.addEventListener("submit",q);c.addEventListener("click",R);
//# sourceMappingURL=index.js.map
